# These are supported funding model platforms

github: adityakdevin               # GitHub Sponsors username
patreon: adityakdevin                 # Patreon username
ko_fi: adityakdevin                     # Ko-fi username
buy_me_a_coffee: adityakdevin           # Buy Me a Coffee username
